server:
  port: 7100

spring:
  mail:
    properties:
      mail:
        smtp:
          debug: true

keycloak:
  realm: apps-dev
  credentials:
    secret: ZHokp4c6gUUTqiPqjGW1zoxRJSs0x7zz

logging:
  level:
    io.craigmiller160.emailservice: DEBUG
    io.craigmiller160.webutils: DEBUG