server:
  port: 7100

spring:
  datasource:
    host: localhost
    port: 30001
    username: user
    password: password
  mail:
    properties:
      mail:
        smtp:
          debug: true

oauth2:
  auth-server-host: https://localhost:7003
  client-key: b68d4457-e6db-4c6c-9a08-efb56fe3981e
  client-secret: 532f5839-2327-4de0-8912-f23df24ede22

logging:
  level:
    io.craigmiller160.authmanagementservice: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG