server:
  port: 7100

spring:
  mail:
    properties:
      mail:
        smtp:
          debug: true

logging:
  level:
    io.craigmiller160.emailservice: DEBUG
    io.craigmiller160.webutils: DEBUG
    io.craigmiller160.oauth2: DEBUG