app_deployment:
  appName: email-service
  image: nexus-docker-craigmiller160.ddns.net/email-service:latest
  configMap:
    spring.profiles.active: prod
    spring.config.location: classpath:/config/common/,classpath:/config/prod/
    spring.datasource.host: postgres.infra-prod
    spring.datasource.port: "5432"
    spring.datasource.db-name: email_service_prod
    oauth2.auth-server-host: https://sso-oauth2-server:8443
  onepassworditems:
    - name: email-service-gmail-credentials
      itemPath: vaults/Home Server (Prod)/items/Email Service Gmail Credentials
    - name: email-service-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Email Service OAuth2 Keys
    - name: email-service-postgres
      itemPath: vaults/Home Server (Prod)/items/Postgres Root Account
  secrets:
    - envVariable: CRAIG_EMAILER_PASSWORD
      secretName: email-service-gmail-credentials
      secretKey: password
    - envVariable: spring.datasource.username
      secretName: email-service-postgres
      secretKey: username
    - envVariable: spring.datasource.password
      secretName: email-service-postgres
      secretKey: password
    - envVariable: oauth2.client-secret
      secretName: email-service-oauth2-keys
      secretKey: clientSecret
    - envVariable: oauth2.client-key
      secretName: email-service-oauth2-keys
      secretKey: clientKey
  livenessProbe:
    httpGet:
      path: /actuator/health
      port: 8443
      scheme: HTTPS
  ports:
    - containerPort: 8443