app_deployment:
  appName: email-service
  image: nexus-docker-craigmiller160.ddns.net/email-service:latest
  configMap:
    spring.profiles.active: prod
    spring.config.location: classpath:/config/common/,classpath:/config/prod/
    oauth2.auth-server-host: https://sso-oauth2-server:8443
  onepassworditems:
    - name: email-service-gmail-credentials
      itemPath: vaults/Home Server (Prod)/items/Email Service Gmail Credentials
    - name: email-service-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Email Service OAuth2 Keys
  secrets:
    - envVariable: CRAIG_EMAILER_PASSWORD
      secretName: email-service-gmail-credentials
      secretKey: password
    - envVariable: keycloak.credentials.secret
      secretName: email-service-oauth2-keys
      secretKey: kcClientSecret
    - envVariable: keycloak.resource
      secretName: email-service-oauth2-keys
      secretKey: kcClientId
  commonProbe:
    httpGet:
      path: /actuator/health
      port: 8443
      scheme: HTTPS
  ports:
    - containerPort: 8443