server:
  servlet:
    session:
      cookie:
        name: CRAIGSESSIONID
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keys/email-service.p12
    key-store-password: email-service-pass
    use-ssl: true
    enabled: true
    protocol: TLS
    enabled-protocols: TLSv1.2,TLSv1.3
    ciphers: ECDHE-ECDSA-AES256-GCM-SHA384,ECDHE-RSA-AES256-GCM-SHA384,ECDHE-ECDSA-CHACHA20-POLY1305,ECDHE-RSA-CHACHA20-POLY1305,ECDHE-ECDSA-AES128-GCM-SHA256,ECDHE-RSA-AES128-GCM-SHA256,ECDHE-ECDSA-AES256-SHA384,ECDHE-RSA-AES256-SHA384,ECDHE-ECDSA-AES128-SHA256,ECDHE-RSA-AES128-SHA256

spring:
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db-name}
  mail:
    host: smtp.gmail.com
    port: 465
    username: craigmiller.emailer@gmail.com
    password: ${CRAIG_EMAILER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

oauth2:
  client-name: email-service
  insecure-paths: "/actuator/health"
  disable-csrf: true

logging:
  level:
    root: INFO
