spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/email_service_dev
  mail:
    host: smtp.gmail.com
    port: 465
    username: craigmiller.emailer@gmail.com
    password: ${CRAIG_EMAILER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true

oauth2:
  client-name: email-service
  insecure-paths: "/actuator/health"

logging:
  level:
    root: INFO