apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-configmap
data:
  spring.profiles.active: prod
  spring.config.location: classpath:/config/common/,classpath:/config/prod/
  spring.datasource.host: postgres-service.default
  spring.datasource.port: "5432"
  spring.datasource.db-name: email_service_prod
  oauth2.auth-server-host: https://sso-oauth2-server-service:8443
  logging.level.com.zaxxer: DEBUG
