apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: {{ .Values.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: IfNotPresent
          ports:
            {{- range $port := .Values.deployment.ports }}
            - {{ $port }}
            {{- end}}
          envFrom:
            {{- range $configmap := .Values.deployment.configmaps  }}
            - {{ $configmap }}
            {{- end}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.appName }}
  ports:
    {{- range $port := .Values.service.ports }}
    - port: {{ $port.containerPort }}
      targetPort: {{ $port.containerPort }}
    {{- end}}