apiVersion: v1
kind: ConfigMap
metadata:
  name: email-service-configmap
data:
  spring.datasource.host: postgres-service
  spring.datasource.port: "5432"
  spring.datasource.username: user
  spring.datasource.password: password
  oauth2.client-key: 17795450-ff0d-47fe-b23c-dfe6d7f090d8
  oauth2.client-secret: c078af10-7f97-4afb-981d-76ecacb7dbfd