apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
        - name: email-service
          image: craigmiller160.ddns.net:30004/email-service:latest
          envFrom:
            - configMapRef:
                name: email-service-configmap
          env:
            # TODO this one needs a 1password secret
            - name: CRAIG_EMAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: craig-emailer-password
                  key: CRAIG_EMAILER_PASSWORD
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: postgres-root-password
                  key: POSTGRES_ROOT_PASSWORD
            # TODO this one needs a 1password secret
            - name: oauth2.client-secret
              valueFrom:
                secretKeyRef:
                  name: email-service-client-secret
                  key: client-secret
          # TODO how to transfer this over?
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: email-service-service
spec:
  type: NodePort
  selector:
    app: email-service
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30005
      protocol: TCP
