appName: email-service
deployment:
  image: nexus-docker-craigmiller160.ddns.net/email-service:latest
  configMaps:
    - email-service-configmap
  secrets:
    - envVariable: CRAIG_EMAILER_PASSWORD
      secretName: email-service-gmail-credentials
      secretKey: password
    - envVariable: spring.datasource.password
      secretName: postgres-root-account
      secretKey: password
    - envVariable: oauth2.client-secret
      secretName: email-service-client-secret
      secretKey: client-secret
  livenessProbe:
    path: /actuator/health
    port: 8443
    scheme: HTTPS
service:
  type: ClusterIP
  ports:
    - containerPort: 8443
